### PR TITLE
Fix "CD Image Cache" core option not working

### LINKED ISSUE #189: CD Image Cache doesn't work
Pretty straightforward issue. The CD Image Cache option does nothing. I tested both chd and bin+cue formats on Linux and asked someone on Windows to confirm as well. There's no change in memory usage or behavior regardless of the setting's state. The core was fully closed and reopened between checks.

### PR DESCRIPTION
**Pull request by bslenul**
Tested on Windows 10, Sanaki confirmed it working on Linux as well, fixes #189 :)

### CODE REVIEW

**Comment by jdgleaver** [comment]
Erm... What? I already fixed this: https://github.com/libretro/beetle-saturn-libretro/pull/187

The change in this PR should have no effect...

**Comment by bslenul** [comment]
Hm I'm super confused, maybe the core didn't update properly for me and Sanaki when testing this (we're both using different OS so that makes it even weirder)? Or there was something else preventing the core option from working somehow 🤔 

I have no idea but yeah, just deleted my core options file and the .dll and re-downloaded the core from the buildbot and now it seems to work...

So yeah, sorry about that :x Can you confirm @Sanaki ?

**Comment by jdgleaver** [comment]
Heh - no need to apologise! I was also just super confused by what was going on here :)

Anyway, I'm glad the core is working ;)

**Comment by Sanaki** [comment]
Uh... yeah. I have no idea what happened here, but I can confirm the same.

**Pull request closed without merging**
