### PR TITLE
Arcade Racer steering wheel

### PR DESCRIPTION
**Pull request by hiddenasbestos**
Added support for the Arcade Racer steering wheel peripheral.
Tested with Virtua Racing.

Product info here: http://segaretro.org/Arcade_Racer_Joystick

I've mapped the (digital) paddle shifters to L2/R2

### CODE REVIEW

**Comment by hiddenasbestos** [comment]
Re-opened now I know was causing the fault in #76.

**Comment by retro-wertz** [comment]
not to be nit picky here, but  isnt L and R is reversed? normally on a 6-button fighting game with ABC as kick and XYZ as punch, but a controller layout like snes/psx(libretro) C is mapped to L and Z is mapped to R?

**Comment by hiddenasbestos** [comment]
Can't seem to see your comment on github @retro-wertz , hoping this reply works -- 
I've changed the L / R around using Street Fighter as a guide. On Super 
Nintendo the L shoulder button is heavy punch (Saturn's Z button in 
SFAlpha2) and R shoulder on SNES goes to heavy kick (Saturn's C button 
in SFA2). My change maps L shoulder to Saturn Z and R to Saturn C which 
I believe is the correct orientation.

**Comment by ghost** [comment]
yeah i realized i was thinking of something else entirely. ignore that post.

**Pull request merged**
