### PR TITLE
Extra mouse buttons

### PR DESCRIPTION
**Pull request by hiddenasbestos**
Added support for RETRO_DEVICE_ID_MOUSE_BUTTON_4 and RETRO_DEVICE_ID_MOUSE_BUTTON_5

Mapped these controls to the Saturn mouse 'start' button.

Note these new constants are still pending approval by libretro-common / RetroArch as of this post.

### CODE REVIEW

**Comment by inactive123** [comment]
Is there a way to better describe these new mouse buttons? Or is 4/5 as good as it's going to get?

**Comment by hiddenasbestos** [comment]
Hi @twinaphex, it's really inconsistent sadly.

The problem is both that the physical position of these buttons vary from manufacturer to manufacturer - I've owned mice with one on each side, two on top in the vertical configuration, my current mouse has both on the right side (I'm left handed!).

Also names I've seen in APIs are X1/X2 in SDL, they're called 4/5 in Windows RAW API, they're just array indices 3 and 4 in DirectInput. It's not consistent at all!

Mouse 4 and 5 is common UI terminology in my experience of gaming, and are about as clear as you're gonna get I think.

**Comment by inactive123** [comment]
Alright, understandable.

**Comment by inactive123** [comment]
I am asking @Alcaro for some last-minute input, if he agrees with me that we can merge this as-is, I will merge it first in the RetroArch repo, then everywhere else.

**Comment by hiddenasbestos** [comment]
Great, thanks for supporting such a niche feature!

**Comment by inactive123** [comment]
BTW, would you also be interested in adding mouse support to Beetle PSX by any chance? I believe PSX mouse was just a two button mouse, nothing fancy going on there and might be easy to implement considering the similar Mednafen codebase.

**Comment by hiddenasbestos** [comment]
Sure, might be fun to take a look at PSX mouse too! Yeah it's a much simpler design. Seems like there's some good games for it too.

**Pull request merged**
