### PR TITLE
3D Control Pad support

### PR DESCRIPTION
**Pull request by rtissera**
Known issues :
- Mode is hardcoded to "analog". We can assign "mode" switch to SELECT button to allow switching between analog and digital modes. Let me know what you think in the PR comments.
- Left / Right analog triggers analog values are generated from digital values. Is it possible with current libretro/RetroArch architecture to have left/right triggers analog values as source ?

### CODE REVIEW

**Comment by inactive123** [comment]
Unfortunately with the current libretro API, analog values for the shoulder buttons is not possible. It will require an API extension. It's probably possible to dream something up that doesn't require an ABI break, but it's not something you have to do in order to complete the bounty at least.

**Comment by inactive123** [comment]
I am fine with using the select button for something, since it's currently unused anyway since Saturn didn't have a Select button. No objections here.

**Comment by Awakened0** [comment]
As a work around, can the analog triggers also be assigned to up and down on the RetroPad's right stick? It's not used for anything else and that would be a decent way to get analog acceleration and break in Sega Rally. I think right trigger on up and left trigger on down would give you up to accelerate and down to break.

**Comment by rtissera** [comment]
Yes it can be done easily even if it is a bit hacky.
Waiting for more feedback between implementing this.

**Comment by Zer0one** [comment]
I tested the current commit, everything work great but... even if by default not assigned to anything (because the RetroPad doesn't support analog trigger) the Saturn 3D Pad analog trigger should be declared as inputs. If not as a separate entity, maybe togheter as a single axis...

P.S. Sorry for my English....

**Pull request merged**
